# Generated by Django 3.0.6 on 2020-05-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='img/default/default.jpg', upload_to='img'),
        ),
    ]
