# Generated by Django 3.0.6 on 2020-05-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_main_article',
            field=models.BooleanField(default=False),
        ),
    ]
