# Generated by Django 3.0.6 on 2020-05-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200524_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_main_article',
        ),
        migrations.AddField(
            model_name='article',
            name='is_main_in_category',
            field=models.BooleanField(default=False, verbose_name='Главная статья в своей категории(можно поставить только 1)'),
        ),
    ]
