# Generated by Django 3.0.6 on 2020-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200524_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_main_in_homepage',
            field=models.BooleanField(default=False, verbose_name='Главная статья на домашней страницу(всего 3)'),
        ),
    ]
