# Generated by Django 3.0.6 on 2020-06-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200627_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=170, verbose_name='Описание пользователя'),
        ),
    ]
